version: '3.9'

services:
  app:
    build: .
    command: npm start
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
  mongo:
    image: mongo:4.2
    container_name: mongo
    restart: always
    ports:
      - 27017:27017

  

  

  